print("Program starting.")
Name=input("What is your name:")
Number1=input("Enter a floating point number:")
print(float(Number1))
Number2=input("Enter second floating point number:")
print(float(Number2))
print(f"{Name} you gave numbers {Number1} and {Number2}")
Final =(round(float(Number1) * float(Number2), 2))
print(f"Multiplying first and second number will result in product {Final}")
print("Program ending.")